service: sms

plugins: 
  - serverless-iam-roles-per-function
  # - serverless-domain-manager
  - serverless-prune-plugin
  
custom:
  stage: 'prod'
  region: 'ap-south-1'
  prune:
    automatic: ${self:custom.prune_by_stage.${self:custom.stage}.automatic, self:custom.prune_by_stage.other.automatic}
    number: ${self:custom.prune_by_stage.${self:custom.stage}.number, self:custom.prune_by_stage.other.number}
  prune_by_stage:
    prod:
      automatic: true
      number: 3
    other:
      automatic: false
      number: 0
  serverless-aws-resource-names:
    source: mapping.json
  deploymentBucketName: ${self:custom.stage}-${self:custom.region}-s3-4-serverless-deployment
  domains:
    prod: api.${self:custom.region}.hubhello.com
  customDomainBaseMapping:
    prod:
      prod: 'sms'
    other: sms
  serverless-iam-roles-per-function:
    defaultInherit: true
  urls:
    test: v1/test
    
package:
  individually: true
  
provider:
   name: aws
   region: ${opt:region, 'ap-south-1'}
   stage: ${opt:stage, 'prod'}
   runtime: nodejs16.x
   
functions:
  test:
    handler: functions/test.handler
    events:
      - http:
          path: ${self.custom.urls.test}
          method: get
        