service: sms

plugins: 
  - serverless-iam-roles-per-function
  - serverless-aws-resource-names
  # - serverless-domain-manager
  - serverless-add-api-key
  - serverless-prune-plugin
  
custom:
  stage: ${opt:stage, 'stg'}
  region: ${opt:region, 'ap-southeast-2'}
  prune:
    automatic: ${self:custom.prune_by_stage.${self:custom.stage}.automatic, self:custom.prune_by_stage.other.automatic}
    number: ${self:custom.prune_by_stage.${self:custom.stage}.number, self:custom.prune_by_stage.other.number}
  names:
    notificationSNSTopic: ${self:custom.stage}-${self:custom.region}-sns-4-${self:service}--notification-topic
    notificationSNSTopicDLQ: ${self:custom.stage}-${self:custom.region}-sqs-4-${self:service}--notification-sns-topic-dlq
    SMSQueue: ${self:custom.stage}-${self:custom.region}-sqs-4-${self:service}--sms-queue
    SMSDLQ: ${self:custom.stage}-${self:custom.region}-sqs-4-${self:service}--sms-dlq
    snsSqsSharedKeyAlias: alias/${self:custom.stage}-${self:custom.region}-kms-4-${self:service}--sns-sqs-shared
    notificationTopicArn:  'arn:aws:sns:${self:custom.region}:${aws:accountId}:${self:custom.names.notificationSNSTopic}'
  settings:
    stg:
      kmsPolicy: 'KMSAdmin'
    prd:
      kmsPolicy: 'KMSAdmin'
  prune_by_stage:
    stg:
      automatic: true
      number: 10
    prd:
      automatic: true
      number: 3
    other:
      automatic: false
      number: 0
  serverless-aws-resource-names:
    source: mapping.json
  deploymentBucketName: ${self:custom.stage}-${self:custom.region}-s3-4-serverless-deployment
  domains:
    stg: api.${self:custom.region}.hubhello.com
    prd: api.${self:custom.region}.hubhello.com
  customDomainBaseMapping:
    prd:
      prd: 'sms'
    stg:
      stg: 'sms'
    other: 'sms'
  serverless-iam-roles-per-function:
    defaultInherit: true
  secrets:
    smsApiKeySecretName: ${self:custom.stage}-${self:custom.region}-secret-4-${self:service}-service--api-key
  apiKeys:
    - name: ${self:custom.stage}-api-key-4-${self:service}-service
      deleteAtRemoval: false
      value: ${ssm:/aws/reference/secretsmanager/${self:custom.secrets.smsApiKeySecretName}}
      usagePlan:
        name: ${self:custom.stage}-usage-plan-4-${self:service}-service
        throttle:
          burstLimit: 200
          rateLimit: 100
    
package:
  individually: true
  
provider:
  name: aws
  region: ${opt:region, 'ap-southeast-2'}
  stage: ${opt:stage, 'stg'}
  stackName: ${self:custom.stage}-${self:custom.region}-${self:service}-service
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
  logs:
    httpApi: true

   
functions:
  send-sms:
    handler: functions/send-sms.handler
    events:
      - http:
          method: POST
          path: v1/sms/send
          private: true
          cors: true
      - sqs:
          arn:
            Fn::GetAtt:
              - SMSQueue
              - Arn
          batchSize: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:SetSMSAttributes
          - sns:Publish
        Resource: '*'

  bulk-sms-send:
    handler: functions/bulk/send-sms.handler
    environment:
      notificationTopicArn: ${self:custom.names.notificationTopicArn}
    events:
      - http:
          method: POST
          path: v1/bulk/sms/send
          private: true
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: 
          - ${self:custom.names.notificationTopicArn}

resources: ${file(serverless/resources.yml)}
    